### ISSUE TITLE
compatibility change

### ISSUE THREAD

**Issue by jagDanJu** [alisonrafael/metabase-db2-driver#1]
Hey @alisonrafael
can you please update your driver to work with the current version of metabase?
I need downgrade metabase to 0.33.7.3, because it does not work with your driver.

following error occurs:

 java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :db2 

Thanks!

**Comment by alisonrafael** [comment]
Try this https://github.com/alisonrafael/metabase-db2-driver/releases/download/v1.1.0/db2.metabase-driver.jar
